"""Initial mifhwfkhwgf

Revision ID: b026d8c3e820
Revises: cd7d5572d887
Create Date: 2024-08-29 17:16:39.103094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b026d8c3e820'
down_revision = 'cd7d5572d887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.drop_column('foto_url')
        batch_op.drop_column('telefon_numarasi')
        batch_op.drop_column('is_giris_tarihi')
        batch_op.drop_column('mail_adresi')
        batch_op.drop_column('gorevi')
        batch_op.drop_column('ev_adresi')
        batch_op.drop_column('izin_bilgileri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('izin_bilgileri', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ev_adresi', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('gorevi', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('mail_adresi', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_giris_tarihi', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('telefon_numarasi', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
