"""Initial migrafrwe

Revision ID: cd7d5572d887
Revises: 
Create Date: 2024-08-29 12:11:35.501686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7d5572d887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.alter_column('is_giris_tarihi',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.alter_column('is_giris_tarihi',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
